A=zeros(10,10);
for i=1:10
   for j=1:10
      A(i,j)=(i-2)*(j-3)+0.5;
   end
end


% TRANSLATE THE ELEMENTS IN A SO THAT EACH ELEMENT IN A ROW IS SHIFTED TO
% THE NEXT COLUMN TO THE RIGHT. THE LAST ELEMENT IN A ROW BECOMES THE FIRST
% ELEMENT IN THE SAME ROW.


% % FIND THE MAXIMUM AND MINIMUM VALUES IN A USING THE BUILT-IN MAX AND MIN
% FUNCTIONS % CONSULT MATLAB DOCUMENTATION
 


% % TRANSFORM THE ELEMENTS OF A TO INTEGER VALUES % CONSULT MATLAB
% DOCUMENTATION ON FLOOR, CEIL AND ROUND


% FIND ELEMENTS OF A THAT ARE LARGER THAN 0 % CONSULT MATLAB
% DOCUMENTATION: Find Array Elements That Meet a Condition

 
% % FIND ALSO THE INDICES OF THESE ELEMENTS


% DISPLAY THE POSITION OF THESE ELEMENTS GRAPHICALLY to make a binary map
% of what is >0 and <=0


% Another way to make a binary map of what is >0 and <=0


% FIND THE POSITION OF THE ELEMENTS THAT ARE NOT THE SAME IN A AND C % CONSULT MATLAB
% DOCUMENTATION: Find Array Elements That Meet a Condition

C=A;
for i=1:10
   C(i,i)=20;
end
disp('Matrix with 1 where A and C differ');