%%% Signorini stress-strain relation
%%% zeyfa, 09 Sept 2026
%%% mprop: [E, A, c1, c2, c3, c4]
function emod = signorini(mprop, epsilon)
    [c1, c2, c3, c4] = mprop(3:6);
    lambda = 1 + c4 * epsilon;
    emod = c4 * ( ...
        c1 * (1 + 2 * lambda^-3) ...
        + 3 * c2 * lambda^-4 ...
        + 3 * c3 * (-1 + lambda^2 - 2 * lambda^-3 + 2 * lambda^-4) ...
    );
end